#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc


# PATH and OMANIRI variables for Niri session
export OMANIRI_PATH="$HOME/.local/share/omaniri"
export PATH="$OMANIRI_PATH/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin:$PATH"