general {
    lock_cmd = pidof hyprlock || hyprlock -q
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = niri msg action power-on-monitors
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 550
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0
    on-resume = brightnessctl -rd '*::kbd_backlight'
}

listener {
    timeout = 550
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors && brightnessctl -r
}

# listener {
   # timeout = 1200                            # 20 min
   # on-timeout = systemctl suspend # command to run when timeout has passed
# }
