--ozone-platform=wayland
--ozone-platform-hint=wayland
--ignore-gpu-blocklist
--enable-smooth-scrolling
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,TouchpadOverscrollHistoryNavigation
