# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgba(798186ee) rgba(caccccee)
$inactiveBorderColor = rgb(1e1e1e)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    rounding = 6
    rounding_power = 3

    shadow {
      enabled = yes
      range = 16
      color = rgba(00000052)
    }
}
